### ISSUE TITLE
Pink-gorilla 

### ISSUE THREAD

**Issue by awb99** [mauricioszabo/atom-chlorine#114]
Hi!

I watched a talk from you discussing integration of charts and reagent components to chlorine.

We work on a related project 
https://github.com/pink-gorilla

We also use reagent to display data in
A web clojure notebook ui. 

We are working on a plugin system to
render arbitrary data in reagent render
components that can be added at runtime. 

I think there is a good overlap in what we
are trying to do. Should we talk?

**Comment by mauricioszabo** [comment]
Great! Let's talk about it. Are you on Clojurians slack? If so, you can find me there and we can talk better than by GH issues :)
