### ISSUE TITLE
Autocomplete on dynamic vars shows regex errors

### ISSUE THREAD

**Issue by seancorfield** [mauricioszabo/atom-chlorine#132]
Using the built-in auto-complete, not Compliment, start typing a dynamic var name like `*test-me*` in a Clojure file with a connected REPL and you'll see red error messages in the console about invalid regex expressions.

**Comment by mauricioszabo** [comment]
Great catch! I'll probably need to escape special chars on regexp when autocompleting code. I _think_ it'll need to be manually because I don't remember ClojureScript (nor Node.JS) having an "regexp.escape"-like function
