### ISSUE TITLE
Uncaught Error: No protocol method IAssociative.-assoc defined for type string: #unrepl/browsable...

### ISSUE THREAD

**Issue by sparkofreason** [mauricioszabo/atom-chlorine#139]
Getting this error consistently when attempting to use the Inspect Block command. Loading a file works fine. The specifics of the error message depend on the form being evaluated, what is pasted below is for a `def`. Doing an Inspect on `ns` gives "Error: No protocol method IAssociative.-assoc defined for type string: nil", for example. 

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [chlorine](https://github.com/mauricioszabo/atom-chlorine) package 0.4.0

### Stack Trace

Uncaught Error: No protocol method IAssociative.-assoc defined for type string: #unrepl/browsable [#clojure/var charts/statement-type-data {:repl-tooling/... (unrepl.repl$3rcwMcc9rCLOH4gMQfLo21mMbCs/fetch :G__9558)}]

```
At /Users/dave.dixon/.atom/packages/chlorine/lib/cmds.js:36

Error: No protocol method IAssociative.-assoc defined for type string: #unrepl/browsable [#clojure/var charts/statement-type-data {:repl-tooling/... (unrepl.repl$3rcwMcc9rCLOH4gMQfLo21mMbCs/fetch :G__9558)}]
    at Jb (/packages/chlorine/lib/cmds.js:27:65)
    at lc (/packages/chlorine/lib/cmds.js:36:213)
    at Function.S.g (/packages/chlorine/lib/cmds.js:116:36)
    at Function.xh.g (/packages/chlorine/lib/cmds.js:293:99)
    at /packages/chlorine/lib/cmds.js:1141:194
    at Q4 (/packages/chlorine/lib/cmds.js:1544:349)
    at /packages/chlorine/lib/cmds.js:1547:343
    at N4 (/packages/chlorine/lib/cmds.js:1536:818)
    at /packages/chlorine/lib/cmds.js:1547:275
    at W0 (/packages/chlorine/lib/cmds.js:1263:225)
    at /packages/chlorine/lib/cmds.js:1569:371
    at v1 (/packages/chlorine/lib/cmds.js:1277:225)
    at gaa (/packages/chlorine/lib/cmds.js:1284:259)
    at iaa (/packages/chlorine/lib/cmds.js:1285:230)
    at /packages/chlorine/lib/cmds.js:1287:56
    at waa (/packages/chlorine/lib/cmds.js:1302:358)
    at yaa (/packages/chlorine/lib/cmds.js:1304:322)
    at /packages/chlorine/lib/cmds.js:1305:117
    at Fg.g.Te (/packages/chlorine/lib/cmds.js:227:374)
    at Jg (/packages/chlorine/lib/cmds.js:229:237)
    at Function.Kg.g (/packages/chlorine/lib/cmds.js:231:208)
    at /packages/chlorine/lib/cmds.js:1308:450)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12)
```

### Commands

```
  2x -4:11.2.0 core:backspace (input.hidden-input)
     -4:01.9.0 chlorine:connect-clojure-socket-repl (input.hidden-input)
     -3:59.5.0 core:focus-next (input.input-text)
     -3:38.5.0 chlorine:inspect-block (input.hidden-input)
     -3:34.2.0 chlorine:load-file (input.hidden-input)
     -3:31.2.0 chlorine:inspect-block (input.hidden-input)
     -2:59.7.0 chlorine:connect-clojure-socket-repl (input.hidden-input)
     -2:47.8.0 chlorine:load-file (input.hidden-input)
  4x -0:39.2.0 core:backspace (input.hidden-input)
     -0:36.8.0 core:undo (input.hidden-input)
     -0:32.5.0 chlorine:inspect-block (input.hidden-input)
```

### Non-Core Packages

```
atom-java-decompiler 0.1.2 
chlorine 0.4.0 
ink 0.11.8 
lisp-paredit 0.6.0 
parinfer 1.23.0 
split-diff 1.6.1 
```

**Comment by sparkofreason** [comment]
Confirmed that no error occurs when rolling back to 0.3.9.

**Comment by seancorfield** [comment]
@sparkofreason Are you using the built-in `inspect-block` command or the version from my `init.coffee` setup here https://github.com/seancorfield/atom-chlorine-setup ?

If you're using the built-in version, try switching to my version -- it works with 0.4.1 (I literally just used it, ten seconds ago!). I haven't used the built-in version for quite a while and I think most people using REBL are using my command set from that repo above, rather than the built-in versions.

**Comment by seancorfield** [comment]
I just confirmed that the built-in version is broken. @mauricioszabo should probably remove `inspect-block` and `inspect-top-block` and the wrap-in-rebl-submit code and encourage folks to use my add-on versions since there's actually more functionality in my setup: inspect var, inspect namespace, etc.

**Comment by mauricioszabo** [comment]
Do you think it's better to migrate your add-on versions to Chlorine instead, or its better to just remove then?

**Comment by sparkofreason** [comment]
@seancorfield Tried your version, nothing seems to happen. No output, no error. I'm not currently using REBL.

**Comment by sparkofreason** [comment]
@seancorfield However, I am using your version of Inspect Selection, and that does work.

**Comment by mauricioszabo** [comment]
Fixed on v.04.2
