### ISSUE TITLE
Question: why does doc-for not assume built-in doc function?

### ISSUE THREAD

**Issue by seancorfield** [mauricioszabo/atom-chlorine#14]
I was looking at adding a "show source" function and expected to model it on "doc for var" -- but that seems to do it from first principles.

In ProtoREPL, show docs either uses `(doc <varname>)` in a cljs REPL or `(do (require 'clojure.repl) (clojure.repl/doc <varname>))` 

Is there a specific reason `doc-for` doesn't take that (simpler) approach?

ProtoREPL only supports "show source" for Clojure, not cljs, so I would follow the do-require-source approach (and warn on cljs that it is not supported).

Thoughts?

**Comment by mauricioszabo** [comment]
I think that's because I had some issues with `doc` on Cljs - probably could have been an old code (or some old way I was handling ClojureScript) that broke `(doc <varname>)` specifically for ClojureScript.

If you can make it work, I see no issues on using `(doc <varname>)`, so go ahead!

**Comment by seancorfield** [comment]
Closing this since it looks like you've changed how `doc` is implemented anyway.

**Comment by mauricioszabo** [comment]
Well, on CLJS and with shadow-cljs (the only adapter it's supported right now) `doc` is not working properly (or, sometimes, at all), and that's the reason I'm implementing it by hand.
