### ISSUE TITLE
Question: How to connect to both Clojure & Clojurescript REPL 

### ISSUE THREAD

**Issue by ILoveHubGit** [mauricioszabo/atom-chlorine#142]
Hi Mauricio,
I created a project 

`lein new luminus testCljCljs +swagger +kee-frame +kibit +shadow-cljs`

in which I would like to try to port a Clojure library to ClojureScript. Therefore, your chlorine plugin for Atom could be very helpful. However, I can't get it to connect to the ClojureScript REPL.

I started the Clojure REPL with: 

`JVM_OPTS='-Dclojure.server.myrepl={:port,5555,:accept,clojure.core.server/repl}' lein repl`

and the ClojureScript with:

`npx shadow-cljs node-repl`

In the file "socket-repl.port" within the folder .shadow-cljs I can see a port number 34089 and when I try to connect to a REPL in Atom (version 1.43.0) with "Chlorine: Connect (Clojure) socket Repl" it proposes this port on localhost. If I leave it this way I do get a connection to the Clojure Repl.
But if I try to "Chlorine: Connect Embedded" for the ClojureScript Repl nothing happens.

What am I doing wrong?
Thanks in advance

PS: If I initially connect to port 5555, I also can't connect to the ClojureScript Repl

**Comment by mauricioszabo** [comment]
I saw that you're using `lein-shadow` plug-in. I didn't know it existed :)

With shadow-cljs, you probably want something like `npx shadow-cljs watch <some-build-id>`. As you're using this template, it adds some commands to `lein` to work with shadow. Considering this, you have lots of options:

1 - Open `lein` using the `JVM_OPTS='-Dclojure.server.myrepl={:port,5555,:accept,clojure.core.server/repl}' lein repl`, then use the shadow API to compile the code (look for `shadow.devtools.api` or something like that on the official documentation). With this, you can connect toi port `5555` and work on CLJ and CLJS.

2 - Use the command `lein shadow watch app`, and then use Chlorine the same way you would to connect to Clojure, then ClojureScript.

Please note that Chlorine will only connect to ClojureScript if there's a runtime connected to JS. This means that, as you're using Luminous, you need to serve the app, then open the page on the browser, and _only then_ run Connect Embeded :smile: 

So, the full process:

1. Run `lein shadow watch app`
2. Wait a while for the app to compile (you'll see something like `[:app] Build completed.` on console)
3. Connect Socket REPL on Chlorine
4. On `core.clj`, type `(-main)` and evaluate this form. This will start the luminous webserver on port `3000`. Got to `localhost:3000` on your browser. You'll see the _Congratulations, your Luminus site is ready_ on the browser if everything is correct
5. On Chlorine, use "Connect Embedded". Chose the "app" target

**Comment by mauricioszabo** [comment]
Also, I just found: if you want to stop the webserver, *do not use* the built-in `(stop-app)` please!

This will stop some handler on the Socket REPL too... if you want to stop the server (before a refresh or something) evaluate only the first form of `stop-app`, or evaluate this:

```
(doseq [component (:stopped (mount/stop))]
    (log/info component "stopped"))
```

Please, let me know if you're able to connect. If so, I'll update the documentation :)

**Comment by ILoveHubGit** [comment]
Thanks for you answer.
I figured it out. It is working now.
So after created a project with `lein new luminus testCljCljs +swagger +kee-frame +kibit +shadow-cljs`, you can connect to both Repls CLJ & CLJS by following the next actions:

1. lein shadow watch app
2. lein run
3. Open the website in a browser, typically http://localhost:3000
4. In Atom use Chlorine: Connect Socket Repl
5. Then in Atom use Chlorine: Connect Embedded

Now both Repls are connected and the webpages gets updates when cljs files are changed.

**Comment by mdiin** [comment]
Just wanted to chime in here and say that Chlorine is the first environment where I have had a satisfactory Clojure+Clojurescript setup - your plugin convinced me to ditch emacs. :open_mouth: You are doing a great job @mauricioszabo, thanks!

I am using deps/CLI and shadow-cljs, which is a great combination by the way.

**Comment by ILoveHubGit** [comment]
I fully agree with @mdiin . I also switched from emacs to atom and just finished some changes in https://github.com/daviddpark/clj-json-patch which is a very nice Clojure library to create json+patch messages.
I used chlorine to add support for ClojureScript and just added a pull request.

Thanks @mauricioszabo

**Comment by mauricioszabo** [comment]
Great, thanks for the comments :). Also, if you think there's some clarification needed on the README of the project or anything, tell me (or open a PR - I'll be glad to have more documentation).
