### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by sederholms** [mauricioszabo/atom-chlorine#183]
With the most recent atom version when installing chlorine I get:

npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
npm ERR! request to https://codeload.github.com/mauricioszabo/atom-chlorine/legacy.tar.gz/v0.6.2 failed, reason: self signed certificate in certificate chain

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.atom/.apm/_logs/2020-05-11T07_36_24_783Z-debug.log

---------------------------------------------------

**Comment by mauricioszabo** [comment]
How did you install Atom? By the official website, or with some package manager?

This does not seem a problem with Chlorine, see if it was reported on Atom's issues - I can't even reproduce here, to be honest...

**Comment by sederholms** [comment]
Atom was installed from the official site, a zip package for macs. I then proceeded to update the command line NPM and that seemed to solve the issue.
