### ISSUE TITLE
Usage section on project's readme page only showing Unix-y instructions

### ISSUE THREAD

**Issue by SarmBoJim** [mauricioszabo/atom-chlorine#190]
Hi,
I've just started using Chlorine but had problems getting a socket REPL started as I was unaware that
the instructions for starting a socket REPL with Leiningen as mentioned in the "Usage" section on the main readme page only worked for Unix-like systems and not on Windows:
JVM_OPTS='-Dclojure.server.myrepl={:port,5555,:accept,clojure.core.server/repl}' lein repl

I learned how to get it done on Windows by posting on Clojureverse: 
https://clojureverse.org/t/need-help-starting-a-socket-repl-with-lein-on-windows-for-chlorine-use

Would be nice to have instructions on the readme page for anyone trying to get it running on Windows with little programming experience.

**Comment by mauricioszabo** [comment]
Hi, just added this information on the README: https://github.com/mauricioszabo/atom-chlorine/blob/abd70ef31a5af49c30993fcb56c7228691325a27/README.md#usage

Do you believe it's enough?

**Comment by SarmBoJim** [comment]
Hi Maurico,
That looks great! Hopefully that should help anyone else like me, trying to
get started ;)
