### ISSUE TITLE
REPL not connected for ClojureScript. You can connect a REPL using 'Connect Socket REPL' command, or 'Connect Embedded' command

### ISSUE THREAD

**Issue by rtacconi** [mauricioszabo/atom-chlorine#217]
Hi,

I am using Chlorine 0.9.4. I have an app Clojure app using deps.edn and shadow-cljs. This is the shadow-cljs.edn )it is in the root of the project:

```
{:source-paths ["src"]

 :dependencies [[binaryage/devtools "0.9.10"]
                [reagent "0.8.1"]
                [cljs-http "0.1.46"]]
 :dev-http {8080 "resources/public"}
 :builds
 {:app
   {:target :browser
        :output-dir "resources/public/js"
        :asset-path "/js"
        :modules
        {:main {:entries [app.core]}}
        }}}

```
The project structure is this:
```
├── LICENSE.md
├── README.md
├── deps.edn
├── node_modules
│   ├── asap
│   ├── asn1.js
...
│   └── xtend
├── package.json
├── resources
│   └── public
├── shadow-cljs.edn
├── shell.nix
└── src
    ├── app
    └── rtacconi
```
rtacconi directory has a compojure config to serve index.html and expose a JSON endpoint. `app` directory is where I have a reagent app.

I use the Clojure app in the REPL easily. However, I tried `connect to REPL` and `connect embedded` and I always get the error reported on the subject above.

**Comment by mauricioszabo** [comment]
Ok, let see: you're starting a Clojure socket REPL with `clj` command and then connecting to it? Or are you starting a shadow-cljs "watch" process and then connecting to the port that Chlorine auto detects for you?

If it's the former, it's probably what's wrong. Chlorine (currently - I'm looking for alternatives) only connects to a single "Clojure" REPL, and in this case, it's the REPL that's started from `clj`. If you connect to the REPL that's started from shadow-cljs it will probably work.

Just to be sure: when you run `Connect embedded`, no error message appears?

**Comment by mauricioszabo** [comment]
@rtacconi were you able to figure out the problem?

**Comment by rtacconi** [comment]
No I gave up, I have no idea why it is not working, I get no extra info.
