### ISSUE TITLE
You can connect a REPL using Connect Socket REPL command, or Connect Embedded command

### ISSUE THREAD

**Issue by rtacconi** [mauricioszabo/atom-chlorine#218]
Hi,

I am using Chlorine 0.9.4. I have an app Clojure app using deps.edn and shadow-cljs. This is the shadow-cljs.edn )it is in the root of the project:

```
{:source-paths ["src"]

 :dependencies [[binaryage/devtools "0.9.10"]
                [reagent "0.8.1"]
                [cljs-http "0.1.46"]]
 :dev-http {8080 "resources/public"}
 :builds
 {:app
   {:target :browser
        :output-dir "resources/public/js"
        :asset-path "/js"
        :modules
        {:main {:entries [app.core]}}
        }}}

```
The project structure is this:
```
├── LICENSE.md
├── README.md
├── deps.edn
├── node_modules
│   ├── asap
│   ├── asn1.js
...
│   └── xtend
├── package.json
├── resources
│   └── public
├── shadow-cljs.edn
├── shell.nix
└── src
    ├── app
    └── rtacconi
```
rtacconi directory has a compojure config to serve index.html and expose a JSON endpoint. `app` directory is where I have a reagent app.

I use the Clojure app in the REPL easily. However, I tried `connect to REPL` and `connect embedded` and I always get the error:

REPL not connected for ClojureScript.
You can connect a REPL using 'Connect Socket REPL' command, or 'Connect Embedded' command

**Comment by mauricioszabo** [comment]
Probably you have two socket-repls opened in this config: one for `deps.edn` and another for the shadow-cljs process. Can you confirm me if this is the case?

If so, you're probably connecting to the `deps.edn` REPL then trying to run `Connect Embedded`. This will not work - you have to connect to the `shadow-cljs` REPL to be able to use ClojureScript. One thing that I normally do is to run the shadow-cljs compiler inside Clojure, so then I can connect to a single REPL both for the backend and the frontend...

**Comment by rtacconi** [comment]
Yes, I confirm that this is the case. I was able to connect to two REPLs (shadow and deps.edn) using two VS code editors. What you are saying makes sense and probably in any editor, I would have to run shadow-cljs from clojure. I will try again and I will let you know. Thank you.
