### ISSUE TITLE
Issue dereferencing an atom in a multithread scenario.  

### ISSUE THREAD

**Issue by mhumming** [mauricioszabo/atom-chlorine#222]
Hello, I was testing the thread-safe nature of atoms.  The following two code snippets work correctly on nrepl. 

(def x (atom 0))
(repeatedly 20
  (fn [] (future (swap! x inc))))    ;put atom in multiple threads with future 
(deref x)

(dotimes [i 10] (.start (Thread. (fn [] (println i)))))

Thank-you for your work on Atom-Chlorine!  Very simple to set-up...

**Comment by mauricioszabo** [comment]
What's the error that's happening? Just so that maybe it's easier to debug the problem :)

**Comment by mhumming** [comment]
Yep, okay!  
In the first example, the atom should dereference to a value of 20: **Chlorine is giving me a value of 5**.
(def x (atom 0))
(repeatedly 20
(fn [] (future (swap! x inc)))) ;put atom in multiple threads with future
(deref x)

In the second example: **Chlorine is printing to the terminal but not to the Chlorine Repl**.
(dotimes [i 10] (.start (Thread. (fn [] (println i)))))

Cheers!

**Comment by mauricioszabo** [comment]
Ok, nothing to do here...

Chlorine (at least, for now) does not realize the full lazy sequence. In this case, it means that `repeatedly` will only realize a number of info. That's completely normal: you should use `doall` if you want to realize everything. This will also breaks on the REPL, if you do not print the result for example:

```clojure
(def x (atom 0))
(def something
  (repeatedly 20
    (fn [] (future (swap! x inc)))) ;put atom in multiple threads with future
)
(deref x) ;; => 0
```

The second case is also a problem: nowadays, there isn't a REPL implementation that redirects STDOUT for threads (Socket-REPL, prepl, and nREPL all behave the same). So, nothing to do here: it's a limitation of Clojure.

I will keep this issue open to document these behaviors, but it's not really a bug. For example, if you evaluate `repeatedly` and then click on the `...` link that appears on Chlorine, you'll see that eventually you'll realize the full sequence and then the result will be 20 :+1:

**Comment by mauricioszabo** [comment]
Explained the problem here: https://github.com/mauricioszabo/repl-tooling/blob/master/doc/FAQ.md#when-i-evaluate-multi-thread-code-sometimes-the-result-is-wrong
