### ISSUE TITLE
Enable re-opening Console

### ISSUE THREAD

**Issue by peter-kehl** [mauricioszabo/atom-chlorine#32]
Hi Maurício,

Thank you for Chlorine.

Say you connect Chlorine to socket repl. It opens the console. Later you close the console by a mistake.

Currently I can't see a way to re-open the console, other than disconnect and connect again. Could you allow re-opening, please.

**Comment by seancorfield** [comment]
When you close the Console it disconnects the REPL automatically (at least in the *master* version) so there is no hidden REPL/Console to re-open.

**Comment by mauricioszabo** [comment]
@peter-kehl currently when you close the console it disconnects from the REPL indeed. What is the behavior you expected? Can you give the version of Chlorine you're using?

**Comment by mauricioszabo** [comment]
Related to: https://github.com/JunoLab/atom-ink/issues/198, so I don't duplicate their behaviour if its accepted

**Comment by mauricioszabo** [comment]
Fixed on v0.1.2, added a config to decide where to open the console and fixed issues with the disconnect.
