### ISSUE TITLE
Allow splitting Console pane

### ISSUE THREAD

**Issue by peter-kehl** [mauricioszabo/atom-chlorine#33]
Hi Maurício,

Thank you for Chlorine.

Could you enable splitting Console into two (and multiple) panes, please.

Why? On a small screen, I have several views of the frequently visited buffers. I use a layout of three panes: two main columns, and one narrow wide row at the bottom. I'd have the Console at the bottom row for most recent results. To see the history, I'd keep another view in one of the columns, but I'd switch to it only if I needed it. That way I don't need to resize panes, I only switch between them. Much more productive.

**Comment by mauricioszabo** [comment]
Part of it is fixed on v0.1.2

The second part (be able to have the console into two and multiple panes) I don't think it can be done: it's a limitation of Ink, the package I use to create the console. So, unless it becomes supported on Ink, I'll have to add multiple hacks and keep lots of state that would probably confuse the code a lot.

As for me, when I use a small screen a use the wonderful package "Hey Pane", that have a command called `toggle-focus-of-active-pane`. Here's an example:

![ezgif-5-c79443fd7559](https://user-images.githubusercontent.com/138037/57574165-245bc600-740a-11e9-9552-f1d9c7e64fdf.gif)

**Comment by peter-kehl** [comment]
Thank you for your work. Also for suggesting  "Hey Pane."
