### ISSUE TITLE
developing.md slightly inaccurate regarding copying of resources directory

### ISSUE THREAD

**Issue by sogaiu** [mauricioszabo/atom-chlorine#37]
Attempting to follow the instructions in developing.md, yielded the following error when compiling:

```
IllegalArgumentException: Cannot open <nil> as a Reader.
```

It turns out that the instructions say to:

```
cp repl-tooling/resources .
```

but that doesn't typically work without some flag for cp (e.g. -a or -r).

Initially, I failed to understand that the directory was the target of copying and copied the contained file instead.  This lead to blob-contents failing and seeing the above error.

Please update the instructions appropriately :)

**Comment by mauricioszabo** [comment]
Thanks! Fixed already!

**Comment by sogaiu** [comment]
Thanks!

I didn't know that -a could be placed after the path specifiers, but I have learned something new :)
