### ISSUE TITLE
remove src/repl-tooling from .gitignore?

### ISSUE THREAD

**Issue by sogaiu** [mauricioszabo/atom-chlorine#41]
When searching via ag (and perhaps other tools?), it seems more convenient for src/repl-tooling to not be ignored, but it is included in .gitignore, so it appears to be under certain invocations.

For example, I was looking for 'connect-unrepl', but the following:

```shell
ag -l connect-unrepl
```

returns:

```shell
src/chlorine/repl.cljs
```

With src/repl-tooling removed from .gitignore, the command returns:

```shell
repl-tooling/test/repl_tooling/editor_integration/connection_test.cljs
repl-tooling/src/repl_tooling/editor_integration/connection.cljs
src/chlorine/repl.cljs
```

At least for someone trying to read and understand both chlorine and repl-tooling, the latter results seem more useful :)

According to git log, it looks like src/repl-tooling was added to .gitignore after repl-tooling was arranged to be a submodule.  I'm not sure, but doesn't git ignore submodules by default?  I don't know if it's trustworthy, but the following seemed to suggest so:

https://stackoverflow.com/a/7912101

Are there other reasons to have src/repl-tooling in .gitignore?

**Comment by mauricioszabo** [comment]
Not really. Removed it on https://github.com/mauricioszabo/atom-chlorine/pull/42/commits/841c42286b122bdf54df03f6aaf6fd80bc301246

**Comment by sogaiu** [comment]
Thanks!
