### ISSUE TITLE
dynamic vars *1 *2 *3 not evaluating properly

### ISSUE THREAD

**Issue by scotts777** [mauricioszabo/atom-chlorine#48]
The dynamic vars *1, *2, and *3  always return nil instead of recent values.

**Comment by mauricioszabo** [comment]
Although unrepl and socket REPL supports then, these were never meant to work on Chlorine - it needs to send some commands to set namespace and file position (row/col), so even if they do work, it's almost sure that they won't work.

Why do you need then?

**Comment by scotts777** [comment]
Ok.  I don't necessarily need them.  Sometimes I like to use them for REPL interaction convenience when experimenting with things.  But I wouldn't say it is a big deal.  By the way,  thanks for the great work on Chlorine.
