### ISSUE TITLE
Clarify REPL editability?

### ISSUE THREAD

**Issue by KingMob** [mauricioszabo/atom-chlorine#79]
I tried out Chlorine today, and was very surprised that while typing at the REPL, there was no way to evaluate anything typed.

I chatted w/ Sean Corfield on Slack, and he told me Chlorine can't be typed into. If that's the case, perhaps a visual indicator would be helpful? Either something to indicate the functionality is not there yet, or if you believe people shouldn't type into REPLs, remove entirely the ability to type into it? Currently, it's a bit misleading.

**Comment by KingMob** [comment]
(I'm personally rooting for being able to type in the REPL, fwiw 😄 )

**Comment by mauricioszabo** [comment]
I was looking at this issue and found out: when we're connected on both Clojure and ClojureScript, how do we know which REPL to run the code?

I began to always send code to Clojure, but it seems strange specially when we have a "mostly-clojurescript" project; also, when I tried to implement it, there was a problem when I switched from "eval in editor" and "eval in REPL" (eval in editor changes namespaces all the time)..... I'm thinking that I'll simply disable the editing capabilities until I can find a better way.
