### ISSUE TITLE
Typing url strings throws autocomplete errors on each character after http://

### ISSUE THREAD

**Issue by ChrisBronkhorst** [mauricioszabo/atom-chlorine#85]
When typing url strings in a connected clojurescript session, I get the following error.

Failed to read: clojure.lang.ExceptionInfo: repl-input.cljs [line 2, col 39] Invalid symbol: https:/a. {:type :reader-exception, :ex-kind :reader-error, :file "repl-input.cljs", :line 2, :col 39}
TypeError: cljs.core.ns_name.split is not a function

Is it possible to check that you are currently typing a symbol and only do namespace lookups then, and not while typing strings?

**Comment by mauricioszabo** [comment]
Yes, I'm able to reproduce. Thanks, I'll see a fix. As the autocomplete for ClojureScript, for now, is something "half-baked", I'll probably just ignore exceptions

**Comment by mauricioszabo** [comment]
Just to be sure, this error is happening on the console tab, right?

**Comment by ChrisBronkhorst** [comment]
Well, thanks for fixing so quickly, I didn't even have time to confirm that, yes, errors showing up in the console.

**Comment by mauricioszabo** [comment]
Great! So it's fixed on version 0.1.11. You were lucky, I was going to publish a new version yesterday with other fixes, and as I saw that your bug was something quite easy to fix, it entered on the same release :)
