### ISSUE TITLE
Connect to repl without a prompt

### ISSUE THREAD

**Issue by cldwalker** [mauricioszabo/atom-chlorine#88]
Hi. Thanks for the excellent library! I have a minor feature request to make. I'd like to be able to connect to a clojure repl without having to go through a prompt as I almost always use the same port. Would you be open to a PR with one of the two approaches?

1. Allow for two configurations: a number to specify a default port and a boolean that when set to true allows for connecting without a prompt e.g. the connect command skips right to firing `chlorine.repl.connect!`
2. Making [chlorine.repl.connect!](https://github.com/cldwalker/atom-chlorine/commit/87c71bdc7d362fc5462ec874bae6fe4d11670da9) public so [users can create their own command](https://github.com/cldwalker/atomfiles/blob/master/lib/clojure.js#L70-L73)

I'd prefer option 1 because it correctly activates chlorine on initial use while I haven't figured out how to active chlorine with option 2. Also interested if there are other options you can think of. Cheers

**Comment by mauricioszabo** [comment]
Ok, you can activate it with:

```js
const unloadedChlorine = atom.packages.getLoadedPackage('chlorine')
unloadedChlorine.activateNow()
unloadedChlorine.activationPromise.then(() => {
  atom.commands.add('atom-text-editor', 'me:chlorine-connect-without-prompt', () => {
    const chlorine = atom.packages.getLoadedPackage('chlorine').mainModule
    chlorine.repl.connect_bang('localhost', '5555')
  })
})

```

I don't thing I would go for `1`, but see no problem on option `2`. I'll check it and probably also make public the command to connect to embedded CLJS, so users could pass a command and make it work with figwheel, figwheel-main, weasel, and other envs too :)

**Comment by cldwalker** [comment]
Option 2 works fine. Thanks for the tip on activateNow(). I do see [Package.activate() is implemented w/ activateNow()](https://github.com/atom/atom/blob/2d3e332b889bce1e458d154efa608016f47d8b9d/src/package.js#L199-L227) so perhaps activateNow() doesn't do some minor setup. Ideally, we could activate packages with personal commands more cleanly. I tried the following in my init.js but it didn't work:
```js
const p = atom.packages.getLoadedPackage('chlorine')
p.activationCommands['atom-workspace'].push('me:chlorine-connect-without-prompt')
```
Still learning some of atom's API. activateNow() works good enough for now

Look forward to having repl connection for clj and cljs being public :)

**Comment by mauricioszabo** [comment]
I'll close this issue in favor of https://github.com/mauricioszabo/atom-chlorine/issues/94 :)
