### ISSUE TITLE
Make `chlorine.repl.connect!` public

### ISSUE THREAD

**Issue by mauricioszabo** [mauricioszabo/atom-chlorine#94]
This API: [chlorine.repl.connect!](https://github.com/cldwalker/atom-chlorine/commit/87c71bdc7d362fc5462ec874bae6fe4d11670da9) could be public [users can create their own command](https://github.com/cldwalker/atomfiles/blob/master/lib/clojure.js#L70-L73)

**Comment by cldwalker** [comment]
Hi. Would you like me to submit a PR for this?

**Comment by mauricioszabo** [comment]
Yes, please, it would help a lot!

**Comment by mauricioszabo** [comment]
Ok, I believe that starting on `v0.10.0`, it's possible to make this public, as Chlorine is now always activated. Will try to wrap up something :)

**Comment by mauricioszabo** [comment]
Implemented on v0.11.2
